# 1번 12세 이하인 여자 환자 목록 출력하기
# 오답노트: IFNULL 함수를 쓰는게 더 깔끔
[풀이 1]
SELECT PT_NAME, PT_NO, GEND_CD, AGE, 
    CASE
        WHEN TLNO IS NULL THEN 'NONE'
        ELSE TLNO
    END AS TLNO
FROM PATIENT
WHERE GEND_CD = 'W' AND AGE <= 12
ORDER BY AGE DESC, PT_NAME ASC;

[풀이 2]
SELECT PT_NAME, PT_NO, GEND_CD, AGE,
       IFNULL(TLNO, 'NONE') AS TLNO
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME ASC;

# 2번 흉부외과 또는 일반외과 의사 목록 출력하기
[풀이 1]
SELECT DR_NAME, DR_ID, MCDP_CD, HIRE_YMD
FROM DOCTOR
WHERE MCDP_CD IN('CS', 'GS')
ORDER BY HIRE_YMD DESC, DR_NAME ASC;

# 3번 경기도에 위치한 식품창고 목록 출력하기
[풀이 1]
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N')
FROM FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME LIKE '%경기%'
ORDER BY WAREHOUSE_ID;

# 4번 조건에 맞는 회원수 구하기
# 오답노트: BETWEEN A AND B 하면 A 이상 B 이하다. 파이썬 같이 (include, exclude) 아님.
[풀이 1]
SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE JOINED LIKE '2021-%' AND (AGE BETWEEN 20 AND 29);

# 5번 아픈 동물 찾기
[풀이 1]
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'
ORDER BY ANIMAL_ID;

# 6번 역순 정렬하기
[풀이 1]
SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC;

# 7번 이름이 없는 동물의 아이디
[풀이 1]
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NULL
ORDER BY ANIMAL_ID;

# 8번 인기 있는 아이스크림
[풀이 1]
SELECT FLAVOR
FROM FIRST_HALF
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID ASC;

# 9번 가장 비싼 상품 구하기
[풀이 1]
SELECT MAX(PRICE) AS MAX_PRICE
FROM PRODUCT;

# 10번 상위 n개 레코드
[풀이 1]
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 0, 1;

[풀이 2]
SELECT NAME
FROM ANIMAL_INS
WHERE DATETIME = (SELECT MIN(DATETIME)
                    FROM ANIMAL_INS);


# 11번 이름이 있는 동물의 아이디
[풀이 1]
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
ORDER BY ANIMAL_ID;


# 12번 동물의 아이디와 이름
[풀이 1]
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

# 13번 어린 동물 찾기
[풀이 1]
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION != 'Aged';

# 14번 강원도에 위치한 생산공장 목록 출력하기
[풀이 1]
SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
FROM FOOD_FACTORY
WHERE ADDRESS LIKE '강원도%'
ORDER BY FACTORY_ID ASC;

# 15번 여러 기준으로 정렬하기
[풀이 1]
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME ASC, DATETIME DESC;

# 16번 나이 정보가 없는 회원 수 구하기
[풀이 1]
SELECT COUNT(*)
FROM USER_INFO
WHERE AGE IS NULL;

# 17번 조건에 맞는 도서 리스트 출력하기
[풀이 1]
SELECT BOOK_ID, PUBLISHED_DATE
FROM BOOK
WHERE (PUBLISHED_DATE LIKE '2021-%') AND (CATEGORY = '인문'); 

# 18번 잔챙이 잡은 수 구하기
[풀이 1]
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE LENGTH <= 10 OR LENGTH IS NULL;