# 1번 12세 이하인 여자 환자 목록 출력하기
# 오답노트: IFNULL 함수를 쓰는게 더 깔끔
[풀이 1]
SELECT PT_NAME, PT_NO, GEND_CD, AGE, 
    CASE
        WHEN TLNO IS NULL THEN 'NONE'
        ELSE TLNO
    END AS TLNO
FROM PATIENT
WHERE GEND_CD = 'W' AND AGE <= 12
ORDER BY AGE DESC, PT_NAME ASC;

[풀이 2]
SELECT PT_NAME, PT_NO, GEND_CD, AGE,
       IFNULL(TLNO, 'NONE') AS TLNO
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME ASC;

# 2번 흉부외과 또는 일반외과 의사 목록 출력하기
[풀이 1]
SELECT DR_NAME, DR_ID, MCDP_CD, HIRE_YMD
FROM DOCTOR
WHERE MCDP_CD IN('CS', 'GS')
ORDER BY HIRE_YMD DESC, DR_NAME ASC;

# 3번 경기도에 위치한 식품창고 목록 출력하기
[풀이 1]
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N')
FROM FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME LIKE '%경기%'
ORDER BY WAREHOUSE_ID;

# 4번 조건에 맞는 회원수 구하기
# 오답노트: BETWEEN A AND B 하면 A 이상 B 이하다. 파이썬 같이 (include, exclude) 아님.
[풀이 1]
SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE JOINED LIKE '2021-%' AND (AGE BETWEEN 20 AND 29);

# 5번 아픈 동물 찾기
[풀이 1]
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'
ORDER BY ANIMAL_ID;

# 6번 역순 정렬하기
[풀이 1]
SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC;

# 7번 이름이 없는 동물의 아이디
[풀이 1]
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NULL
ORDER BY ANIMAL_ID;

# 8번 인기 있는 아이스크림
[풀이 1]
SELECT FLAVOR
FROM FIRST_HALF
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID ASC;

# 9번 가장 비싼 상품 구하기
[풀이 1]
SELECT MAX(PRICE) AS MAX_PRICE
FROM PRODUCT;

# 10번 상위 n개 레코드
[풀이 1]
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 0, 1;

[풀이 2]
SELECT NAME
FROM ANIMAL_INS
WHERE DATETIME = (SELECT MIN(DATETIME)
                    FROM ANIMAL_INS);


# 11번 이름이 있는 동물의 아이디
[풀이 1]
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
ORDER BY ANIMAL_ID;


# 12번 동물의 아이디와 이름
[풀이 1]
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

# 13번 어린 동물 찾기
[풀이 1]
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION != 'Aged';

# 14번 강원도에 위치한 생산공장 목록 출력하기
[풀이 1]
SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
FROM FOOD_FACTORY
WHERE ADDRESS LIKE '강원도%'
ORDER BY FACTORY_ID ASC;

# 15번 여러 기준으로 정렬하기
[풀이 1]
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME ASC, DATETIME DESC;

# 16번 나이 정보가 없는 회원 수 구하기
[풀이 1]
SELECT COUNT(*)
FROM USER_INFO
WHERE AGE IS NULL;

# 17번 조건에 맞는 도서 리스트 출력하기
[풀이 1]
SELECT BOOK_ID, PUBLISHED_DATE
FROM BOOK
WHERE (PUBLISHED_DATE LIKE '2021-%') AND (CATEGORY = '인문'); 

# 18번 잔챙이 잡은 수 구하기
[풀이 1]
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE LENGTH IS NULL;

# 19번 잡은 물고기 중 가장 큰 물고기의 길이 구하기
# 오답노트1 : RPAD는 RPAD(문자열, 총길이, 채울문자)와 같이 쓰며, 문자열을 특정 길이만큼 채우는 함수다.
# 여기서는 단순히 두 문자열을 이어주는 CONCAT이 옳다.
# 오답노트2 : 서브쿼리 이용할 거면 DISTINCT 써줘야 한다. 안 쓰면 최대값이 두 개인 경우 두 줄 출력함.
# 오답노트3 : 최대 길이만 출력하면 되므로, WHERE도 필요가 없다.
[풀이 1]
SELECT CONCAT(MAX(LENGTH), 'cm') AS MAX_LENGTH  
FROM FISH_INFO

[풀이 2]
SELECT CONCAT(LENGTH, 'cm') AS MAX_LENGTH
FROM FISH_INFO
ORDER BY LENGTH DESC LIMIT 1;

[풀이 3]
SELECT DISTINCT CONCAT(LENGTH, 'cm') AS MAX_LENGTH
FROM FISH_INFO
WHERE LENGTH = (SELECT MAX(LENGTH)
                FROM FISH_INFO);

# 20번 평균 일일 대여 요금 구하기
[풀이 1]
SELECT  ROUND(AVG(DAILY_FEE), 0) AS AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = 'SUV';

# 21번 특정 옵션이 포함된 자동차 리스트 구하기
[풀이 1]
SELECT *
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%네비게이션%'
ORDER BY CAR_ID DESC;

# 22번 과일로 만든 아이스크림 고르기
# 오답노트: JOIN 문법 좀 외우자!!
[풀이 1]
SELECT ICECREAM_INFO.FLAVOR
FROM ICECREAM_INFO
JOIN FIRST_HALF
ON ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR
WHERE FIRST_HALF.TOTAL_ORDER > 3000 AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based';

# 23번 Python 개발자 찾기
# 꿀팁: 컬럼 IN (값)으로 많이 쓰지만 뒤집어도 된다는 사실..
[풀이 1]
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPER_INFOS
WHERE SKILL_1 = 'Python' OR SKILL_2 = 'Python' OR SKILL_3 = 'Python'
ORDER BY ID;

[풀이 2]
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPER_INFOS
WHERE 'Python' IN (SKILL_1, SKILL_2, SKILL_3)
ORDER BY ID;

# 24번 모든 레코드 조회하기
[풀이 1]
SELECT *
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

# 25번 잡은 물고기의 평균 길이 구하기
[풀이 1]
SELECT ROUND(AVG(IFNULL(LENGTH, 10)), 2) AS AVERAGE_LENGTH
FROM FISH_INFO;

# 26번 한 해에 잡은 물고기 수 구하기
[풀이 1]
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE TIME LIKE '2021%';

# 27번 최댓값 구하기
[풀이 1]
SELECT DATETIME AS 시간
FROM ANIMAL_INS
ORDER BY DATETIME DESC LIMIT 1;

# 28번 자동차 대여 기록에서 장기/단기 대여 구분하기
# 오답노트1: 날짜를 서로 뺄 때는 DATEDIFF 함수를 써야 제대로 계산이 된다.
# 오답노트2: 날짜 계산이니까 뺀 후에 +1해야 일수 구할 수 있는 거 잊지 말고.
[풀이 1]
SELECT HISTORY_ID, CAR_ID, START_DATE, END_DATE,
    CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) >= 29 THEN '장기 대여'
        ELSE '단기 대여'
    END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE LIKE '2022-09%'
ORDER BY HISTORY_ID DESC;

# 29번 가장 큰 물고기 10마리 구하기
[풀이 1]
SELECT ID, LENGTH
FROM FISH_INFO
ORDER BY LENGTH	DESC, ID ASC
LIMIT 0, 10;

# 30번 조건에 부합하는 중고거래 댓글 조회하기
[풀이 1]
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, R.CREATED_DATE
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_REPLY AS R
ON B.BOARD_ID = R.BOARD_ID
WHERE B.CREATED_DATE LIKE '2022-10%'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;

# 31번 특정 형질을 가지는 대장균 찾기
# 오답 노트: 아니 여기도 비트연산이 되는구나?
[풀이 1]
SELECT COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE GENOTYPE & 2 = 0 AND (GENOTYPE & 4 != 0 OR GENOTYPE & 1 != 0);